# Generated by Django 5.0.6 on 2024-06-19 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='notification_preferences',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='privacy_settings',
        ),
    ]
